services:
#  hotovec.orders.api:
#    image: hotovec.orders.api
#    container_name: orders
#    ports:
#      - "8080:8080"
#    build:
#      context: .
#      dockerfile: src/Hotovec.Orders.Api/Dockerfile
#    depends_on:
#      - mongodb
#    networks:
#      - app_network
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: crypto_password
    networks:
      - app_network

#networks:
#  app_network:
#    driver: bridge
